const CREATE_USER = 'CREATE_USER';
const CREATE_TASK = 'CREATE_TASK';
const DO_TASK = 'DO_TASK';
const UNDO_TASK = 'UNDO_TASK';
const RENAME_TASK = 'RENAME_TASK';
const RENAME_USER = 'RENAME_USER';

export { CREATE_USER, CREATE_TASK, DO_TASK, UNDO_TASK, RENAME_TASK, RENAME_USER };
