const CREATE_USER = 'CREATE_USER';
const CREATE_TASK = 'CREATE_TASK';
const DO_TASK = 'DO_TASK';
const UNDO_TASK = 'UNDO_TASK';
const RENAME_TASK = 'RENAME_TASK';
const RENAME_USER = 'RENAME_USER';

export {
  CREATE_TASK, RENAME_TASK, DO_TASK, UNDO_TASK,
  CREATE_USER, RENAME_USER
};
