const CREATE_USER = 'CREATE_USER';
const CREATE_TASK = 'CREATE_TASK';
const DO_TASK = 'DO_TASK';
const UNDO_TASK = 'UNDO_TASK';
const DELETE_TASK = 'DELETE_TASK';
const RENAME_TASK = 'RENAME_TASK';
const RENAME_USER = 'RENAME_USER';
const TOGGLE_WEEK_VISIBILITY = 'TOGGLE_WEEK_VISIBILITY';
const SET_WEEK_VISIBILITY = 'SET_WEEK_VISIBILITY';

export {
  CREATE_TASK, RENAME_TASK, DO_TASK, UNDO_TASK, DELETE_TASK,
  CREATE_USER, RENAME_USER,
  TOGGLE_WEEK_VISIBILITY, SET_WEEK_VISIBILITY
};
